import subprocess
import sys
#subprocess.run("python co11_91.py", shell=True )
#subprocess.run("python co7_53.py", shell=True )
#subprocess.run("python co19_29.py", shell=True )
#subprocess.run("python co17_43.py", shell=True )
#subprocess.run("python co13_77.py", shell=True )
#subprocess.run("python co31_41.py", shell=True )
#subprocess.run("python co23_67.py", shell=True )
#subprocess.run("python co49_59.py", shell=True )
#subprocess.run("python co37_83.py", shell=True )
#subprocess.run("python co47_73.py", shell=True )
#subprocess.run("python co61_71.py", shell=True )
#subprocess.run("python co79_89.py", shell=True )

start = 100000
subprocess.Popen(["start", "cmd", "/k", "python mod91.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod49.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod19.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod31.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod37.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod67.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod13.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod73.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod11.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod29.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod47.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod83.py" ], shell=True)

subprocess.Popen(["start", "cmd", "/k", "python mod23.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod53.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod41.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod89.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod59.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod71.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod17.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod77.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod7.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod43.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod61.py" ], shell=True)
subprocess.Popen(["start", "cmd", "/k", "python mod79.py" ], shell=True)